# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          key: yarn-v1-
      - run:
          name: Install NPM modules
          command: yarn
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/v1
      - run:
          name: Test
          command: |
            yarn lint
            yarn test --forceExit
      - run:
          name: Build
          command: yarn build

