/**
 * React Static Boilerplate
 * Copyright (c) Konstantin Tarkus | MIT License
 */

/**
 * Note: This file is automatically replaced with the content
 * generated by routes-loader.js Webpack plugin during a build.
 */
export default {};
